name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# Avoid overlapping runs on the same ref (optional)
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Lox Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: |
            experimental-features = nix-command flakes

      # Main test run using default.nix (non-flake)
      - name: Run tests (nix-shell)
        run: |
          set -euo pipefail
          nix-shell --pure --command "cd lox/ && dune runtest --no-buffer"
        # If you need environment variables, add:
        # env:
        #   DUNE_CACHE: disabled

      - name: Print artifact summary
        if: always()
        run: |
          echo "Dune exit code captured above. If this step runs, earlier steps completed."
